--BOL_CXC_ETL                   TD:P
--v6.1.2.6.4.7
DECLARE
  FUNCTION f_et(p_tabla VARCHAR2) RETURN BOOLEAN IS
    v NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v
      FROM user_tables
     WHERE table_name = p_tabla;
    RETURN(v != 0);
  END;
  FUNCTION p_ect_ob_N(p_tabla VARCHAR2, p_campo VARCHAR2) RETURN BOOLEAN IS
    v NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v
      FROM user_tab_columns
     WHERE table_name = p_tabla
       AND nullable = 'N'
       AND column_name = p_campo;
    RETURN(v != 0);
  END;
  PROCEDURE p_bt(p_tabla VARCHAR2) IS
  BEGIN
    IF f_et(p_tabla) THEN
      EXECUTE IMMEDIATE 'DELETE FROM ' || p_tabla || ' WHERE nombre_informe = ''BOL_CXC_ETL'' AND tipo_despliegue = ''P''';
    END IF;
  END;
BEGIN
  IF p_ect_ob_n('GI_INFORMES_USUARIOS_QUERY', 'USUARIO') THEN
    RAISE_APPLICATION_ERROR(-20501, 'IMPORTANTE: Esta SQL requiere entorno 6.4.2 o superior.');
  END IF;
  p_bt('GI_INFORMES_USUARIOS_QUERY');
  p_bt('GI_INFORMES_BASE');
  p_bt('GI_INFORMES_GRUPOS_COLUMNAS');
  p_bt('GI_IDIOMAS');
  p_bt('GI_INFORMES_PLUG_IN_SECTORES');
  p_bt('GI_INFORMES_PLUG_IN_DET');
  p_bt('GI_INFORMES_PLUG_IN');
  DELETE FROM gi_inf_usuarios_guardados_lin l WHERE l.nombre_informe = 'BOL_CXC_ETL' AND l.tipo_despliegue_informe = 'P' AND EXISTS (SELECT 1 FROM gi_inf_usuarios_guardados_cab c WHERE c.nombre_informe = 'BOL_CXC_ETL' AND c.codigo = l.codigo AND c.tipo_despliegue_informe = 'P' AND c.tipo_despliegue = 'P');
  DELETE FROM gi_inf_usuarios_guardados_cab WHERE nombre_informe = 'BOL_CXC_ETL' AND tipo_despliegue_informe = 'P' AND tipo_despliegue = 'P';
  DELETE FROM valor_por_defecto_bloque_lin l WHERE programa = 'U_GENINF_RUN:P:BOL_CXC_ETL' AND tipo_despliegue = 'P';
  DELETE FROM valor_por_defecto_bloque_cab l WHERE programa = 'U_GENINF_RUN:P:BOL_CXC_ETL' AND tipo_despliegue = 'P';
  p_bt('GI_INFORMES_USUARIOS');
INSERT INTO GI_INFORMES_USUARIOS(NOMBRE_INFORME,DESC_INFORME,ORIENTACION,PREDETERMINADO,MARGEN_SUPERIOR,MARGEN_INFERIOR,MARGEN_IZQUIERDA,MARGEN_DERECHA,NEGRITA_CABECERA,NEGRITA_OBS,NEGRITA_FECHA,ESPACIO_ENTRE_COLUMNAS,NEGRITA_DATOS_CUERPO,NEGRITA_TITULOS_CUERPO,RAYAS_SUBTOTALES,RAYAS_TOTALES,NEGRITA_SUBCABECERAS,SUBRAYADO_SUBCABECERAS,NEGRITA_SUBTOTALES,NEGRITA_TOTALES,IMPRIMIR_NOMBRE_EMPRESA,FORMATO_EXCEL,TAMANO_CABECERA,TAMANO_OBS,TAMANO_FECHA,TAMANO_DATOS_CUERPO,TAMANO_SUBCABECERAS,FECHA_ULT_MODIFICACION,IMPRIMIR_CABECERA,TIPO_DESPLIEGUE_PADRE,VERSION_CF) VALUES ('BOL_CXC_ETL','ETL- Cuentas x Cobrar CxC','V','N',0,0,0,0,'S','S','S',2,'N','S','S','S','N','N','S','S','N','L',12,10,8,8,8,TO_DATE('10-12-2025 16:19:20', 'DD-MM-YYYY HH24:MI:SS'),'T','P','$PNTPKLIB$ASIDE%CTRL(FTES:00001:');
UPDATE gi_informes_usuarios SET bbdd_info = 'v6.1.2.6.4.7-130391:90437' WHERE nombre_informe = 'BOL_CXC_ETL' AND tipo_despliegue = 'P';
INSERT INTO GI_INFORMES_BASE(NOMBRE_INFORME,QUERY_FROM,QUERY_WHERE,VERSION_GENERADOR) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','situacion_apunte = ''D'' AND NVL(status_remesado, ''N'') = ''N'' AND documento_vivo = ''S''',2);
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,CAMPO_DE_FILTRO,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,LISTA_VALORES,SOLO_UNO,CABECERA,NOMBRE_FILTRO,ID_COLUMNA,ORDEN_FILTRO,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','CODIGO_CLIENTE','CODIGO CLIENTE',2,'S','N','N',15,'CLIENTES','N','N','CODIGO CLIENTE',1,2,'CODIGO_CLIENTE','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,CAMPO_DE_FILTRO,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,SOLO_UNO,TIPO_FILTRO,CABECERA,NOMBRE_FILTRO,ID_COLUMNA,ORDEN_FILTRO,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','DOCUMENTO','DOCUMENTO',3,'S','N','N',20,'N','C','N','DOCUMENTO',2,5,'DOCUMENTO','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,CAMPO_DE_FILTRO,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,LISTA_VALORES,SOLO_UNO,TIPO_FILTRO,CABECERA,NOMBRE_FILTRO,ID_COLUMNA,ORDEN_FILTRO,VALOR_DEFECTO_FILTRO,FORMULA_VALOR_DEF_FILTRO,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','EMPRESA','EMPRESA',1,'S','N','N',5,'EMPRESAS_CONTA','N','V','N','EMPRESA',3,1,'''001,002,003,004''','S','EMPRESA','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,CAMPO_DE_FILTRO,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,MASCARA,SOLO_UNO,CABECERA,NOMBRE_FILTRO,ID_COLUMNA,ORDEN_FILTRO,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','FECHA_FACTURA','FECHA FACTURA',4,'S','N','N',10,'DF','N','N','FECHA FACTURA',4,3,'FECHA_FACTURA','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,CAMPO_DE_FILTRO,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,MASCARA,SOLO_UNO,CABECERA,NOMBRE_FILTRO,ID_COLUMNA,ORDEN_FILTRO,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','FECHA_VENCIMIENTO','FECHA VENCIMIENTO',5,'S','N','N',10,'DF','N','N','FECHA VENCIMIENTO',5,4,'FECHA_VENCIMIENTO','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,MASCARA,SOLO_UNO,CABECERA,ID_COLUMNA,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','IMPORTE','IMPORTE',6,'N','N',14,'999G999G990D00','N','N',6,'IMPORTE_6','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,MASCARA,SOLO_UNO,CABECERA,ID_COLUMNA,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','IMPORTE_PDTE','IMPORTE PDTE',7,'N','N',14,'999G999G990D00','N','N',7,'IMPORTE_PDTE_7','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,MASCARA,SOLO_UNO,CABECERA,ID_COLUMNA,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','IMPORTE_IMPAGADO','IMPORTE IMPAGADO',8,'N','N',14,'999G999G990D00','N','N',8,'IMPORTE_IMPAGADO_8','N','N');
INSERT INTO GI_INFORMES_USUARIOS_QUERY(NOMBRE_INFORME,NOMBRE_TABLA,NOMBRE_COLUMNA,TITULO_COLUMNA,ORDEN_APARICION,SUBTOTAL,TOTAL,LONGITUD_MAXIMA,MASCARA,SOLO_UNO,CABECERA,ID_COLUMNA,CODIGO_VARIABLE_FILTRO,SALTO_PAGINA,P_SALTO_PAGINA) VALUES ('BOL_CXC_ETL','V_HISTORICO_COBROS','IMPORTE_COBRADO','IMPORTE COBRADO',9,'N','N',14,'999G999G990D00','N','N',9,'IMPORTE_COBRADO_9','N','N');
INSERT INTO VALOR_POR_DEFECTO_BLOQUE_CAB(CODIGO,EMPRESA,USUARIO,PROGRAMA,BLOQUE,DESCRIPCION,PUBLICA) VALUES (2918,'004','EMERCADO','U_GENINF_RUN:P:BOL_CXC_ETL','BOL_CXC_ETL','ETL-Envio email - todas las emp','S');
INSERT INTO VALOR_POR_DEFECTO_BLOQUE_LIN(CODIGO,CAMPO,VALOR,PROGRAMA,FORMULA) VALUES (2918,'V:F_EMPRESA','001,002,003,004','U_GENINF_RUN:P:BOL_CXC_ETL','''001,002,003,004''');
COMMIT;
END;
/
