-- Revisar la query para evaluar reporte de cartera
SELECT TIPO_P,FECHA_VENCIMIENTO,TIPO_TRANSACCION,CODIGO_PROVEEDOR,D_CODIGO_PROVEEDOR,CARACTER_ASIENTO,DOCUMENTO,DOCUMENTO_COMPLETO,FECHA_FACTURA,BANCO,P_IMPORTE,DIVISA_ORIGEN,P_IMPORTE_DIVISA,SERIE_JUSTIFICANTE,JUSTIFICANTE,ESTADO,EMPRESA,FECHA_ASIENTO,DIARIO,NUMERO_ASIENTO_BORRADOR,NUMERO_LINEA_BORRADOR,CODIGO_CUENTA,CONCEPTO,IMPORTE,IMPORTE_ENDOSADO,IMPORTE_PAGADO,IMPORTE_SUSTITUIDO,IMPORTE_DIVISA,IMPORTE_PAGADO_DIVISA,IMPORTE_ENDOSADO_DIVISA,IMPORTE_SUSTITUIDO_DIVISA,MARCA_PUNTEO,FECHA_VALOR_DIVISA,STATUS_PROPUESTA,STATUS_BLOQUEO,NUMERO_PROPUESTA,FECHA_PROPUESTA,D_TIPO_TRANSACCION,NUM_CHEQUE,D_CARACTER_ASIENTO,D_BANCO,BANCO_ASEGURADOR,D_BANCO_ASEGURADOR,NUMERO_DIRECCION,D_NUMERO_DIRECCION,VALOR_CAMBIO,DOCUMENTO_VIVO 
FROM (SELECT A.* ,(SELECT RAZON_SOCIAL FROM BANCOS WHERE CODIGO_RAPIDO = A.BANCO AND EMPRESA = A.EMPRESA) D_BANCO,(SELECT RAZON_SOCIAL FROM BANCOS WHERE CODIGO_RAPIDO = A.BANCO_ASEGURADOR AND EMPRESA = A.EMPRESA) D_BANCO_ASEGURADOR,(SELECT NOMBRE FROM CARACTERES_ASIENTO WHERE CODIGO = A.CARACTER_ASIENTO AND EMPRESA = A.EMPRESA) D_CARACTER_ASIENTO,(SELECT P.NOMBRE FROM PROVEEDORES P WHERE P.CODIGO_RAPIDO = A.CODIGO_PROVEEDOR AND P.CODIGO_EMPRESA = A.EMPRESA) D_CODIGO_PROVEEDOR,(SELECT Z.NOMBRE FROM DOMICILIOS_PAGO_PROVEEDOR Z WHERE Z.CODIGO_RAPIDO = A.CODIGO_PROVEEDOR AND Z.NUMERO_DIRECCION = A.NUMERO_DIRECCION AND EMPRESA = A.EMPRESA) D_NUMERO_DIRECCION,(SELECT NOMBRE FROM TIPOS_TRANSACCIONES WHERE CODIGO = A.TIPO_TRANSACCION) D_TIPO_TRANSACCION, F_PAGOS_CAMBIOS(
PKPANTALLAS.GET_VARIABLE_ENV_VARCHAR2('CAMBIO_ACTUAL'),
PKPANTALLAS.GET_VARIABLE_ENV_VARCHAR2('CAMBIO_ASEGURADO'),
PKPANTALLAS.GET_VARIABLE_ENV_DATE('FECHA_VALOR'),
PKPANTALLAS.GET_VARIABLE_ENV_VARCHAR2('DIVISA_EMPRESA'),
PKPANTALLAS.GET_VARIABLE_ENV_NUMBER('DECIMALES_EMPRESA'),
DIVISA_ORIGEN,
IMPORTE_DIVISA,
IMPORTE_PAGADO_DIVISA,
VALOR_CAMBIO,
DOCUMENTO_VIVO,
IMPORTE_DIV_NO_ASEGURADO,
VALOR_CAMBIO_NO_ASEG,
IMPORTE_DIVISA_ASEGURADO,
IMPORTE_PDTE_DIVISA,
IMPORTE,
IMPORTE_ENDOSADO,
IMPORTE_SUSTITUIDO,
IMPORTE_PAGADO) P_IMPORTE,TO_CHAR(V_IMPORTE_DIVISA, PKMASCARAS.IMPORTES(15, 4, DIVISA_ORIGEN)) P_IMPORTE_DIVISA 
FROM V_HISTORICO_PAGOS_PREV A) A 
WHERE EMPRESA='004' AND SITUACION_APUNTE='D' 
and exists (select 1 from CENTROS_GRUPO_CCONT G where G.CODIGO_GRUPO = '0401' and G.CODIGO_CENTRO = A.CARACTER_ASIENTO and G.EMPRESA = '004') 
AND NOT EXISTS(SELECT 1 FROM BLOQUEO_PROVEEDORES WHERE EMPRESA='004' AND CODIGO_PROVEEDOR=A.CODIGO_PROVEEDOR AND USUARIO='EMERCADO' AND (F_CURRENT_DATE BETWEEN DESDE_FECHA AND HASTA_FECHA)) 
AND DOCUMENTO_VIVO = 'S'  
order by FECHA_VENCIMIENTO,TIPO_TRANSACCION,CODIGO_PROVEEDOR,DOCUMENTO