-- query para ACUMULADOS_CUENTAS_DIVISAS
SELECT ESTADO, CUENTA, DIVISA, EJERCICIO, TIPO_PERIODO, NUMERO, CARACTER_ASIENTO, ACUMULADO_DEBE, ACUMULADO_HABER
FROM ACUMULADOS_CUENTAS
WHERE EMPRESA ='004' AND ESTADO ='BOL'
AND EJERCICIO = 2025


SELECT EJERCICIO, TIPO_PERIODO, NUMERO, CARACTER_ASIENTO, sum(ACUMULADO_DEBE) acum_debe, sum(ACUMULADO_HABER) acum_haber
FROM ACUMULADOS_CUENTAS
WHERE EMPRESA ='004' 
AND ESTADO ='BOL'
AND EJERCICIO = 2025
and cuenta like '11%'
group by EJERCICIO, TIPO_PERIODO, NUMERO, CARACTER_ASIENTO


/*********************************************************/


SELECT CODIGO_CENTRO 
FROM CENTROS_GRUPO_CCONT
where EMPRESA='004' AND CODIGO_GRUPO='0401' 

/************** para tabla centros y grupos balance *******************/
SELECT codigo, nvl(razon_social2, nvl(razon_social, nombre)) d_centro_contable , empresa, GRUPO_BALANCE, estado, d_grupo_balance
FROM (select caracteres_asiento.*, (select nvl(g.razon_social2, g.descripcion) nomb  FROM GRUPOS_CCONT g where g.empresa =caracteres_asiento.empresa and g.codigo= caracteres_asiento.grupo_balance) d_grupo_balance from caracteres_asiento ) caracteres_asiento 
WHERE empresa in ('004','001','002','003')

/*********************************/
(select nvl(c.razon_social2, nvl(c.razon_social, c.nombre))
from caracteres_asiento c where c.empresa=ACUMULADOS_CUENTAS.EMPRESA and c.codigo=ACUMULADOS_CUENTAS.CARACTER_ASIENTO)

(select GRUPO_BALANCE
from caracteres_asiento c where c.empresa=ACUMULADOS_CUENTAS.EMPRESA and c.codigo=ACUMULADOS_CUENTAS.CARACTER_ASIENTO)

select codigo, (nvl(grupos_ccont.razon_social2, grupos_ccont.descripcion)) DESCRIPCION_VI
FROM GRUPOS_CCONT
where empresa ='004'
/*********************************************************/
nombre cuenta: (select nombre from cuentas where empresa=HISTORICO_DETALLADO_APUNTES.EMPRESA AND codigo=HISTORICO_DETALLADO_APUNTES.CODIGO_CUENTA)

centro de coste:  NVL(((SELECT CENTRO_COSTE FROM HISTORICO_DETALLADO_COSTE WHERE EMPRESA=HISTORICO_DETALLADO_APUNTES.EMPRESA AND CODIGO_CUENTA=HISTORICO_DETALLADO_APUNTES.CODIGO_CUENTA AND NUMERO_ASIENTO_BORRADOR = HISTORICO_DETALLADO_APUNTES.NUMERO_ASIENTO_BORRADOR AND FECHA_ASIENTO = HISTORICO_DETALLADO_APUNTES.FECHA_ASIENTO AND DIARIO = HISTORICO_DETALLADO_APUNTES.DIARIO AND NUMERO_LINEA_BORRADOR = HISTORICO_DETALLADO_APUNTES.NUMERO_LINEA_BORRADOR and rownum = 1)),0)

SELECT EMPRESA,CODIGO_GRUPO,CODIGO_CENTRO,D_CODIGO_CENTRO 
FROM (SELECT CENTROS_GRUPO_CCONT.* ,(select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa=CENTROS_GRUPO_CCONT.empresa and codigo=CENTROS_GRUPO_CCONT.codigo_centro) D_CODIGO_CENTRO FROM CENTROS_GRUPO_CCONT) CENTROS_GRUPO_CCONT WHERE (EMPRESA='004') and (CODIGO_GRUPO='L101')
/*********************************************************/




SELECT EMPRESA,CODIGO,DESCRIPCION_VI,DESCRIPCION,RAZON_SOCIAL2,NOMBRE_COMERCIAL,ESTADO,D_ESTADO,TIPO_ENTIDAD,D_TIPO_ENTIDAD,NIF,DESCRIPCION_ABREVIADA,CALLE_PLAZA_AVENIDA,DIRECCION,NUMERO,ESCALERA,PISO,PUERTA,COD_POSTAL,MUNICIPIO,LOCALIDAD,PROVINCIA,D_PROVINCIA,TELEFONO,FAX,INTERNET,TIPO,
(select nombre from tipos_grupos_Balance where empresa = grupos_ccont.empresa and codigo = grupos_ccont.tipo),CENTRO_CONTABLE_PRIN,D_CENTRO_CONTABLE_PRIN,SUFIJO_N68,PREFIJO_SM_REMESAS,SERIE_TESORERIA,DIGITOS_AJUSTE,IMP_CARGO_IMPAG,SERIE_JUSTIFICANTE,FECHA_BAJA,NUMERO_CERTIFICADO_FIRMA,TIPO_REPARTO,D_TIPO_REPARTO,CENTRO_COSTE,CENTRO_CONTABLE_PORTES,D_CENTRO_CONTABLE_PORTES,PUNTO_OPERACIONAL_SARA,D_PUNTO_OPERACIONAL_SARA,GRUPO_CIERRE,NUMERO_GRUPO,NIF_ENT_DOMINANTE,TIPO_GRUPO_DOMINANTE,TIPO_AGRUP_AUTO,VALIDAR_SERIES_FRAS_RECIBIDAS,VALIDAR_SERIES_FRAS_EMITIDAS,CONTROL_EFECTOS_ASIENTOS,REG_ESPECIAL_65,DEVOLUCION_MENSUAL,ULTIMA_AUTOLIQUID_GE,REGIMEN_FISCAL,D_REGIMEN_FISCAL,NIF_ENTIDAD_SUCEDIDA,RAZON_SOCIAL_ENTIDAD_SUCEDIDA,LONGITUD_JUSTIFICANTE,LONGITUD_CONTADOR_GB,DIAS_PLAZO_VCTO,CAMBIO_OBLIGATORIO_DIVISA2,CONTADOR_FACTURAS_RECIBIDAS,contador_facturas_emitidas,LONG_ASIENTO,LONG_PREFIJO,PREFIJO_NUMERACION_ASIENTOS,TIPO_BORRADO_ASIENTOS,NUMERAR_ASIENTOS_GRABAR,TIPO_CANCELACION_CONTA_FC,CTG,COD_REGISTRO_UAF,COD_AGENCIA_UAF,AUTORIZ_PROPUESTAS_PAGO,PAGOS_PARCIALES_PROP,NIVELES_ASCENDER_DESDE,PERMITIR_FIRMAS_AJENAS,DOBLE_CLAVE_FIRMAS,REQUERIR_AUTORIZADOR_ESPECIAL,SEPARAR_ORI_ASIENTO_AGR_PAGO,INFORME_COMPLETO_ASIENTOS,CENTRO_PIVOTE_MUTUAS,D_CENTRO_PIVOTE_MUTUAS,AGENTE_RETENCION_IB,AGENTE_RETENCION_IG,AGENTE_RETENCION_IVA,AGENTE_RETENCION_SUSS,AGENTE_RETENCION_VIG,INSCRITO_REG_ESP_AFIP,D_INSCRITO_REG_ESP_AFIP,AGENTE_PERCEPCION_IB,UNIDAD_FACEB2B,SUST_PAGOS_DEVENGADOS,FECHA_FIN_AMORTIZACION,CONTAB_UNICA_AMORTIZACION,CONTADOR_CODIGO_INMO,D_CONTADOR_CODIGO_INMO,LONGITUD_CODIGO_INMO,PREFIJO_CODIGO_INMO,CONTADOR_CODINT_INMO,D_CONTADOR_CODINT_INMO,LONGITUD_CODINT_INMO,PREFIJO_CODINT_INMO,PRORRATA_ANUAL,REGUL_ANUAL_DEDUC,EXCESO_EN_COBROS,IMPORTE_MAXIMO_EXCESOS,IMPORTE_MIN_GEN_CARTERA_EXCESO,GENERAR_ND_INGRESOS,EXCL_EXCESO_MOVIMIENTO_COBRO,DESCUENTO_PP_NC_COBROS,FORMA_PAGO_DETRACCIONES,D_FORMA_PAGO_DETRACCIONES,BANCO_DETRACCIONES,D_BANCO_DETRACCIONES,DECIMALES_DETRACCIONES,DESDE_FECHA_PERCEPCION,HASTA_FECHA_PERCEPCION,CONTAB_CFDI_TIMBRADO,CAMBIO_FECHA_FRA_TIMBRADO,CODIGO_CLAVE_DIGITAL,FACTURACION_OFFLINE,NUMERO_AUTORIZACION_DONACIONES,FECHA_AUTORIZACION_DONACIONES,NO_CANCELAR_EJER_DIF,NO_CANCELAR_CON_COBROS,TIPO_IMPUESTO_GB,D_TIPO_IMPUESTO_GB,TIPO_IMPTO_ALM_EXENTO_OBRAS,D_TIPO_IMPTO_ALM_EXENTO_OBRAS,INICIO_FACT_ELECTRONICA,CONTRIBUYENTE_ESPECIAL,AGENTE_RETENCION,max_dif_dias_ent_factura,REQUERIR_UUID_REGISTRO,REQUERIR_UUID_FACTURA,REQUERIR_UUID_ALBFRA,REQUERIR_UUID_REC_CIEGO,REQUERIR_UUID_ALBARAN,REQUERIR_UUID_ASIENTO,DISP_SOCKET_VALIDACION,D_DISP_SOCKET_VALIDACION,PAQUETE_VALIDACION_XML,FECHA_LIMITE_CFDI33_COMPRAS,BLOQUEAR_BORRAR_DOCUMENTOS,BLOQUEAR_BORRAR_PRESUPUESTOS,BLOQUEAR_BORRAR_PEDIDOS,BLOQUEAR_BORRAR_ALBARANES,BLOQUEAR_BORRAR_FACTURAS,IMPUESTOS_X_CODIGO_POSTAL,ANTICIPOS_AUTOM_COMPRAS,BLOQUEAR_BORRAR_REG_FACT_COMP,MAX_DIAS_DIF,DIAS_RET_MESA,DIAS_ENTRE_FAVTA_FAREC,CLAVE_ING_BRUTOS,FECHA_INICIO_ACTIVIDAD,CAPITAL_SOCIAL,RESERVADO_CHAR1,RESERVADO_NUMBER1,RESERVADO_DATE1,COMISION_PA_ND_COBROS,DIAS_LIMITE_RECEP_CP,TOKEN_VALIDACION_XML 
FROM (SELECT GRUPOS_CCONT.* ,(nvl(grupos_ccont.razon_social2, grupos_ccont.descripcion)) DESCRIPCION_VI,(select razon_social from bancos where empresa = grupos_ccont.empresa and codigo_rapido = grupos_ccont.banco_detracciones) D_BANCO_DETRACCIONES,(Select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa = grupos_ccont.empresa and codigo = grupos_ccont.centro_contable_portes) D_CENTRO_CONTABLE_PORTES,(select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa = grupos_ccont.empresa and codigo = grupos_ccont.centro_contable_prin) D_CENTRO_CONTABLE_PRIN,(select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa = grupos_ccont.empresa and codigo = grupos_ccont.centro_pivote_mutuas) D_CENTRO_PIVOTE_MUTUAS,(select nombre from contadores where codigo = grupos_ccont.contador_codigo_inmo) D_CONTADOR_CODIGO_INMO,(select nombre from contadores where codigo = grupos_ccont.contador_codint_inmo) D_CONTADOR_CODINT_INMO,(select ds.nombre_dispositivo from DISPOSITIVOS_SOCKET ds where ds.codigo_dispositivo = grupos_ccont.disp_socket_validacion) D_DISP_SOCKET_VALIDACION,decode(grupos_ccont.estado,NULL,NULL,(select nombre from estados where codigo=grupos_ccont.estado)) D_ESTADO,(SELECT lvfcp.nombre FROM formas_cobro_pago lvfcp WHERE lvfcp.codigo = GRUPOS_CCONT.FORMA_PAGO_DETRACCIONES) D_FORMA_PAGO_DETRACCIONES,(select z.descripcion from afip_regimenes_esp_ret z, empresas_conta e where e.codigo = grupos_ccont.empresa AND z.estado = e.estado AND z.codigo_regimen = grupos_ccont.INSCRITO_REG_ESP_AFIP) D_INSCRITO_REG_ESP_AFIP,decode(grupos_ccont.provincia,NULL,NULL,(select nombre from provincias where estado=grupos_ccont.estado and provincia=grupos_ccont.provincia)) D_PROVINCIA,(SELECT nombre FROM sara_puntos_operacionales WHERE id = grupos_ccont.punto_operacional_sara) D_PUNTO_OPERACIONAL_SARA,(select fe.descripcion from fe_regimen_fiscal_sat fe where fe.codigo = grupos_ccont.regimen_fiscal) D_REGIMEN_FISCAL,(select nombre from tipos_grupos_Balance where empresa = grupos_ccont.empresa and codigo = grupos_ccont.tipo) D_TIPO,(SELECT lvtnif.descripcion FROM tipos_nif lvtnif WHERE lvtnif.tipo = GRUPOS_CCONT.TIPO_ENTIDAD AND lvtnif.estado = GRUPOS_CCONT.ESTADO) D_TIPO_ENTIDAD,(SELECT lvtia.descripcion FROM tipos_impuesto_alm lvtia WHERE lvtia.codigo = GRUPOS_CCONT.TIPO_IMPTO_ALM_EXENTO_OBRAS AND lvtia.empresa = GRUPOS_CCONT.EMPRESA) D_TIPO_IMPTO_ALM_EXENTO_OBRAS,(SELECT DESCRIPCION FROM TIPOS_IMPUESTO_GB WHERE CODIGO = GRUPOS_CCONT.TIPO_IMPUESTO_GB AND EMPRESA = GRUPOS_CCONT.EMPRESA) D_TIPO_IMPUESTO_GB,(SELECT A.NOMBRE FROM TIPOS_REPARTO A WHERE A.EMPRESA = GRUPOS_CCONT.EMPRESA AND A.TIPO_REPARTO = GRUPOS_CCONT.TIPO_REPARTO) D_TIPO_REPARTO FROM GRUPOS_CCONT) GRUPOS_CCONT 
WHERE EMPRESA = '004'

select codigo, (nvl(grupos_ccont.razon_social2, grupos_ccont.descripcion)) DESCRIPCION_VI
FROM GRUPOS_CCONT
where empresa ='004'