-- query para ACUMULADOS_CUENTAS_DIVISAS
SELECT ESTADO, CUENTA, DIVISA, EJERCICIO, TIPO_PERIODO, NUMERO, CARACTER_ASIENTO, ACUMULADO_DEBE, ACUMULADO_HABER
FROM ACUMULADOS_CUENTAS
WHERE EMPRESA ='004' AND ESTADO ='BOL'
AND EJERCICIO = 2025


SELECT EJERCICIO, TIPO_PERIODO, NUMERO, CARACTER_ASIENTO, sum(ACUMULADO_DEBE) acum_debe, sum(ACUMULADO_HABER) acum_haber
FROM ACUMULADOS_CUENTAS
WHERE EMPRESA ='004' 
AND ESTADO ='BOL'
AND EJERCICIO = 2025
and cuenta like '11%'
group by EJERCICIO, TIPO_PERIODO, NUMERO, CARACTER_ASIENTO


/*********************************************************/


SELECT CODIGO_CENTRO 
FROM CENTROS_GRUPO_CCONT
where EMPRESA='004' AND CODIGO_GRUPO='0401' 

SELECT nvl(nombre,RAZON_SOCIAL) nombre , empresa, GRUPO_BALANCE, estado 
FROM caracteres_asiento WHERE codigo ='0401' AND empresa = '004'

(select nvl(c.razon_social2, nvl(c.razon_social, c.nombre))
from caracteres_asiento c where c.empresa=ACUMULADOS_CUENTAS.EMPRESA and c.codigo=ACUMULADOS_CUENTAS.CARACTER_ASIENTO)

(select GRUPO_BALANCE
from caracteres_asiento c where c.empresa=ACUMULADOS_CUENTAS.EMPRESA and c.codigo=ACUMULADOS_CUENTAS.CARACTER_ASIENTO)

/*********************************************************/
nombre cuenta: (select nombre from cuentas where empresa=HISTORICO_DETALLADO_APUNTES.EMPRESA AND codigo=HISTORICO_DETALLADO_APUNTES.CODIGO_CUENTA)

centro de coste:  NVL(((SELECT CENTRO_COSTE FROM HISTORICO_DETALLADO_COSTE WHERE EMPRESA=HISTORICO_DETALLADO_APUNTES.EMPRESA AND CODIGO_CUENTA=HISTORICO_DETALLADO_APUNTES.CODIGO_CUENTA AND NUMERO_ASIENTO_BORRADOR = HISTORICO_DETALLADO_APUNTES.NUMERO_ASIENTO_BORRADOR AND FECHA_ASIENTO = HISTORICO_DETALLADO_APUNTES.FECHA_ASIENTO AND DIARIO = HISTORICO_DETALLADO_APUNTES.DIARIO AND NUMERO_LINEA_BORRADOR = HISTORICO_DETALLADO_APUNTES.NUMERO_LINEA_BORRADOR and rownum = 1)),0)

SELECT EMPRESA,CODIGO_GRUPO,CODIGO_CENTRO,D_CODIGO_CENTRO 
FROM (SELECT CENTROS_GRUPO_CCONT.* ,(select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa=CENTROS_GRUPO_CCONT.empresa and codigo=CENTROS_GRUPO_CCONT.codigo_centro) D_CODIGO_CENTRO FROM CENTROS_GRUPO_CCONT) CENTROS_GRUPO_CCONT WHERE (EMPRESA='004') and (CODIGO_GRUPO='L101')
/*********************************************************/


SELECT HDA.BORRADOR,HDA.NUMERO_LINEA_BORRADOR,HDA.CARACTER_ASIENTO,HDA.CODIGO_ENTIDAD,HDA.DOCUMENTO,HDA.SERIE_JUSTIFICANTE,HDA.JUSTIFICANTE,HDA.CODIGO_CONCEPTO,HDA.CONCEPTO,HDA.DEBE,HDA.DEBE_DIV2,HDA.HABER,HDA.HABER_DIV2,HDA.SALDO,HDA.SALDO_DIV2,HDA.MARCA_PUNTEO,HDA.D_CARACTER_ASIENTO,HDA.UUID,HDA.FECHA_TIMBRADO,HDA.ENTIDAD,HDA.D_CODIGO_ENTIDAD,HDA.FECHA_VALOR,HDA.SIGNO,HDA.IMPORTE,HDA.IMPORTE_DIVISA,HDA.IMPORTE_DIV2_EMPRESA,HDA.HAY_ARCHIVOS,HDA.ID_DIGITAL,HDA.NUMERO_ASIENTO_BORRADOR,HDA.SITUACION_APUNTE,HDA.DIARIO,HDA.FECHA_ASIENTO,HDA.EMPRESA,HDA.ESTADO,HDA.NUMERO_LINEA_RESUMEN,HDA.CODIGO_CUENTA,HDA.DIVISA_ORIGEN,HDA.COMENTARIOS,HDA.ID_ASIENTO,HDA.TIPO_CAMBIO_DIVISA2 FROM ( SELECT NUMERO_LINEA_BORRADOR,CARACTER_ASIENTO,CODIGO_ENTIDAD,DOCUMENTO,SERIE_JUSTIFICANTE,JUSTIFICANTE,CODIGO_CONCEPTO,CONCEPTO,DECODE(SIGNO,'D',IMPORTE,NULL) DEBE, DECODE(SIGNO,'D',IMPORTE_DIV2_EMPRESA,NULL) DEBE_DIV2,DECODE(SIGNO,'H',IMPORTE,NULL) HABER, DECODE(SIGNO,'H',IMPORTE_DIV2_EMPRESA,NULL) HABER_DIV2,SUM(DECODE(signo, 'D', importe, -importe)) 
OVER (PARTITION BY numero_asiento_borrador, fecha_asiento, diario, empresa ORDER BY numero_linea_borrador ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) saldo,SUM(DECODE(signo, 'D', importe_div2_empresa, -importe_div2_empresa)) OVER (PARTITION BY numero_asiento_borrador, fecha_asiento, diario, empresa ORDER BY numero_linea_borrador ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) saldo_div2,DECODE(entidad, 'CL', DECODE(hda.codigo_entidad,NULL,NULL,(SELECT c.nombre FROM clientes c WHERE c.codigo_rapido = hda.codigo_entidad AND c.codigo_empresa = hda.empresa)),'PR', DECODE(hda.codigo_entidad,NULL,NULL,(SELECT prlv.nombre FROM proveedores prlv WHERE prlv.codigo_rapido = hda.codigo_entidad AND codigo_empresa = hda.empresa)),'AG', DECODE(hda.codigo_entidad,NULL,NULL,(SELECT lvag.nombre FROM agentes lvag WHERE lvag.codigo = hda.codigo_entidad AND lvag.empresa = hda.empresa)),'BA', DECODE(hda.codigo_entidad,NULL,NULL,(SELECT lvba.nombre FROM bancos lvba WHERE lvba.codigo_rapido = hda.codigo_entidad AND lvba.empresa = hda.empresa))) d_codigo_entidad,

DECODE(hda.caracter_asiento,NULL,NULL,(SELECT lvcc.nombre FROM caracteres_asiento lvcc WHERE lvcc.codigo = hda.caracter_asiento AND lvcc.empresa = hda.empresa)) D_CARACTER_ASIENTO,

DECODE(situacion_apunte, 'B', '*') borrador, tipo_cambio_divisa2, MARCA_PUNTEO,
  (SELECT HI.UUID FROM HISTORICO_IMPUESTOS HI WHERE HI.NUMERO_ASIENTO_BORRADOR = HDA.NUMERO_ASIENTO_BORRADOR AND HI.FECHA_ASIENTO = HDA.FECHA_ASIENTO AND HI.DIARIO = HDA.DIARIO
   AND HI.EMPRESA = HDA.EMPRESA AND HI.NUMERO_LINEA_BORRADOR = HDA.NUMERO_LINEA_BORRADOR and rownum = 1) UUID,
  decode( (SELECT HI.UUID FROM HISTORICO_IMPUESTOS HI WHERE HI.NUMERO_ASIENTO_BORRADOR = HDA.NUMERO_ASIENTO_BORRADOR AND HI.FECHA_ASIENTO = HDA.FECHA_ASIENTO 
  AND HI.DIARIO = HDA.DIARIO AND HI.EMPRESA = HDA.EMPRESA AND HI.NUMERO_LINEA_BORRADOR = HDA.NUMERO_LINEA_BORRADOR 
  and rownum = 1),null,null,(select TO_CHAR(fecha_certificado,'DD/MM/YYYY HH24:MI:SS') from facturas_ventas_doc where UUID = (SELECT HI.UUID FROM HISTORICO_IMPUESTOS HI
   WHERE HI.NUMERO_ASIENTO_BORRADOR = HDA.NUMERO_ASIENTO_BORRADOR AND HI.FECHA_ASIENTO = HDA.FECHA_ASIENTO AND HI.DIARIO = HDA.DIARIO 
   AND HI.EMPRESA = HDA.EMPRESA AND HI.NUMERO_LINEA_BORRADOR = HDA.NUMERO_LINEA_BORRADOR and rownum = 1))) FECHA_TIMBRADO,
  ENTIDAD,FECHA_VALOR,SIGNO,IMPORTE,IMPORTE_DIVISA,IMPORTE_DIV2_EMPRESA,pkconsgen.hay_archivos_x_id_digital ((select id_digital from historico_impuestos hi where hi.numero_asiento_borrador = HDA.numero_asiento_borrador 
  and hi.fecha_asiento = HDA.fecha_asiento and hi.diario = HDA.diario and hi.empresa = HDA.empresa 
  and hi.numero_linea_borrador = HDA.numero_linea_borrador and id_digital is not null and rownum = 1)) HAY_ARCHIVOS, (SELECT HI.id_digital FROM HISTORICO_IMPUESTOS HI 
  WHERE HI.NUMERO_ASIENTO_BORRADOR = HDA.NUMERO_ASIENTO_BORRADOR AND HI.FECHA_ASIENTO = HDA.FECHA_ASIENTO AND HI.DIARIO = HDA.DIARIO
   AND HI.EMPRESA = HDA.EMPRESA AND HI.NUMERO_LINEA_BORRADOR = HDA.NUMERO_LINEA_BORRADOR) ID_DIGITAL,NUMERO_ASIENTO_BORRADOR,SITUACION_APUNTE,DIARIO,
  FECHA_ASIENTO,EMPRESA,ESTADO,NUMERO_LINEA_RESUMEN,CODIGO_CUENTA,DIVISA_ORIGEN,COMENTARIOS ,NULL id_asiento FROM  HISTORICO_DETALLADO_APUNTES   HDA  WHERE EMPRESA='004'  and  hda.caracter_asiento in
                              (SELECT B.CODIGO_CENTRO FROM CENTROS_GRUPO_CCONT B
                                                        where B.EMPRESA='004' 
                                                          AND B.CODIGO_GRUPO='0401'  ) ) HDA WHERE (HDA.NUMERO_ASIENTO_BORRADOR=19369) and (HDA.DIARIO='CFLP') and (HDA.FECHA_ASIENTO=to_date('15-12-2025','DD-MM-YYYY')) and (HDA.EMPRESA='004') order by numero_linea_borrador


SELECT EMPRESA,CODIGO,DESCRIPCION_VI,DESCRIPCION,RAZON_SOCIAL2,NOMBRE_COMERCIAL,ESTADO,D_ESTADO,TIPO_ENTIDAD,D_TIPO_ENTIDAD,NIF,DESCRIPCION_ABREVIADA,CALLE_PLAZA_AVENIDA,DIRECCION,NUMERO,ESCALERA,PISO,PUERTA,COD_POSTAL,MUNICIPIO,LOCALIDAD,PROVINCIA,D_PROVINCIA,TELEFONO,FAX,INTERNET,TIPO,(select nombre from tipos_grupos_Balance where empresa = grupos_ccont.empresa and codigo = grupos_ccont.tipo),CENTRO_CONTABLE_PRIN,D_CENTRO_CONTABLE_PRIN,SUFIJO_N68,PREFIJO_SM_REMESAS,SERIE_TESORERIA,DIGITOS_AJUSTE,IMP_CARGO_IMPAG,SERIE_JUSTIFICANTE,FECHA_BAJA,NUMERO_CERTIFICADO_FIRMA,TIPO_REPARTO,D_TIPO_REPARTO,CENTRO_COSTE,CENTRO_CONTABLE_PORTES,D_CENTRO_CONTABLE_PORTES,PUNTO_OPERACIONAL_SARA,D_PUNTO_OPERACIONAL_SARA,GRUPO_CIERRE,NUMERO_GRUPO,NIF_ENT_DOMINANTE,TIPO_GRUPO_DOMINANTE,TIPO_AGRUP_AUTO,VALIDAR_SERIES_FRAS_RECIBIDAS,VALIDAR_SERIES_FRAS_EMITIDAS,CONTROL_EFECTOS_ASIENTOS,REG_ESPECIAL_65,DEVOLUCION_MENSUAL,ULTIMA_AUTOLIQUID_GE,REGIMEN_FISCAL,D_REGIMEN_FISCAL,NIF_ENTIDAD_SUCEDIDA,RAZON_SOCIAL_ENTIDAD_SUCEDIDA,LONGITUD_JUSTIFICANTE,LONGITUD_CONTADOR_GB,DIAS_PLAZO_VCTO,CAMBIO_OBLIGATORIO_DIVISA2,CONTADOR_FACTURAS_RECIBIDAS,contador_facturas_emitidas,LONG_ASIENTO,LONG_PREFIJO,PREFIJO_NUMERACION_ASIENTOS,TIPO_BORRADO_ASIENTOS,NUMERAR_ASIENTOS_GRABAR,TIPO_CANCELACION_CONTA_FC,CTG,COD_REGISTRO_UAF,COD_AGENCIA_UAF,AUTORIZ_PROPUESTAS_PAGO,PAGOS_PARCIALES_PROP,NIVELES_ASCENDER_DESDE,PERMITIR_FIRMAS_AJENAS,DOBLE_CLAVE_FIRMAS,REQUERIR_AUTORIZADOR_ESPECIAL,SEPARAR_ORI_ASIENTO_AGR_PAGO,INFORME_COMPLETO_ASIENTOS,CENTRO_PIVOTE_MUTUAS,D_CENTRO_PIVOTE_MUTUAS,AGENTE_RETENCION_IB,AGENTE_RETENCION_IG,AGENTE_RETENCION_IVA,AGENTE_RETENCION_SUSS,AGENTE_RETENCION_VIG,INSCRITO_REG_ESP_AFIP,D_INSCRITO_REG_ESP_AFIP,AGENTE_PERCEPCION_IB,UNIDAD_FACEB2B,SUST_PAGOS_DEVENGADOS,FECHA_FIN_AMORTIZACION,CONTAB_UNICA_AMORTIZACION,CONTADOR_CODIGO_INMO,D_CONTADOR_CODIGO_INMO,LONGITUD_CODIGO_INMO,PREFIJO_CODIGO_INMO,CONTADOR_CODINT_INMO,D_CONTADOR_CODINT_INMO,LONGITUD_CODINT_INMO,PREFIJO_CODINT_INMO,PRORRATA_ANUAL,REGUL_ANUAL_DEDUC,EXCESO_EN_COBROS,IMPORTE_MAXIMO_EXCESOS,IMPORTE_MIN_GEN_CARTERA_EXCESO,GENERAR_ND_INGRESOS,EXCL_EXCESO_MOVIMIENTO_COBRO,DESCUENTO_PP_NC_COBROS,FORMA_PAGO_DETRACCIONES,D_FORMA_PAGO_DETRACCIONES,BANCO_DETRACCIONES,D_BANCO_DETRACCIONES,DECIMALES_DETRACCIONES,DESDE_FECHA_PERCEPCION,HASTA_FECHA_PERCEPCION,CONTAB_CFDI_TIMBRADO,CAMBIO_FECHA_FRA_TIMBRADO,CODIGO_CLAVE_DIGITAL,FACTURACION_OFFLINE,NUMERO_AUTORIZACION_DONACIONES,FECHA_AUTORIZACION_DONACIONES,NO_CANCELAR_EJER_DIF,NO_CANCELAR_CON_COBROS,TIPO_IMPUESTO_GB,D_TIPO_IMPUESTO_GB,TIPO_IMPTO_ALM_EXENTO_OBRAS,D_TIPO_IMPTO_ALM_EXENTO_OBRAS,INICIO_FACT_ELECTRONICA,CONTRIBUYENTE_ESPECIAL,AGENTE_RETENCION,max_dif_dias_ent_factura,REQUERIR_UUID_REGISTRO,REQUERIR_UUID_FACTURA,REQUERIR_UUID_ALBFRA,REQUERIR_UUID_REC_CIEGO,REQUERIR_UUID_ALBARAN,REQUERIR_UUID_ASIENTO,DISP_SOCKET_VALIDACION,D_DISP_SOCKET_VALIDACION,PAQUETE_VALIDACION_XML,FECHA_LIMITE_CFDI33_COMPRAS,BLOQUEAR_BORRAR_DOCUMENTOS,BLOQUEAR_BORRAR_PRESUPUESTOS,BLOQUEAR_BORRAR_PEDIDOS,BLOQUEAR_BORRAR_ALBARANES,BLOQUEAR_BORRAR_FACTURAS,IMPUESTOS_X_CODIGO_POSTAL,ANTICIPOS_AUTOM_COMPRAS,BLOQUEAR_BORRAR_REG_FACT_COMP,MAX_DIAS_DIF,DIAS_RET_MESA,DIAS_ENTRE_FAVTA_FAREC,CLAVE_ING_BRUTOS,FECHA_INICIO_ACTIVIDAD,CAPITAL_SOCIAL,RESERVADO_CHAR1,RESERVADO_NUMBER1,RESERVADO_DATE1,COMISION_PA_ND_COBROS,DIAS_LIMITE_RECEP_CP,TOKEN_VALIDACION_XML 
FROM (SELECT GRUPOS_CCONT.* ,(nvl(grupos_ccont.razon_social2, grupos_ccont.descripcion)) DESCRIPCION_VI,
(select razon_social from bancos where empresa = grupos_ccont.empresa and codigo_rapido = grupos_ccont.banco_detracciones) D_BANCO_DETRACCIONES,(Select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa = grupos_ccont.empresa and codigo = grupos_ccont.centro_contable_portes) D_CENTRO_CONTABLE_PORTES,(select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa = grupos_ccont.empresa and codigo = grupos_ccont.centro_contable_prin) D_CENTRO_CONTABLE_PRIN,(select nvl(razon_social2, nvl(razon_social, nombre))
from caracteres_asiento where empresa = grupos_ccont.empresa and codigo = grupos_ccont.centro_pivote_mutuas) D_CENTRO_PIVOTE_MUTUAS,(select nombre from contadores where codigo = grupos_ccont.contador_codigo_inmo) D_CONTADOR_CODIGO_INMO,(select nombre from contadores where codigo = grupos_ccont.contador_codint_inmo) D_CONTADOR_CODINT_INMO,(select ds.nombre_dispositivo from DISPOSITIVOS_SOCKET ds where ds.codigo_dispositivo = grupos_ccont.disp_socket_validacion) D_DISP_SOCKET_VALIDACION,decode(grupos_ccont.estado,NULL,NULL,(select nombre from estados where codigo=grupos_ccont.estado)) D_ESTADO,(SELECT lvfcp.nombre FROM formas_cobro_pago lvfcp WHERE lvfcp.codigo = GRUPOS_CCONT.FORMA_PAGO_DETRACCIONES) D_FORMA_PAGO_DETRACCIONES,(select z.descripcion from afip_regimenes_esp_ret z, empresas_conta e where e.codigo = grupos_ccont.empresa AND z.estado = e.estado AND z.codigo_regimen = grupos_ccont.INSCRITO_REG_ESP_AFIP) D_INSCRITO_REG_ESP_AFIP,decode(grupos_ccont.provincia,NULL,NULL,(select nombre from provincias where estado=grupos_ccont.estado and provincia=grupos_ccont.provincia)) D_PROVINCIA,(SELECT nombre FROM sara_puntos_operacionales WHERE id = grupos_ccont.punto_operacional_sara) D_PUNTO_OPERACIONAL_SARA,(select fe.descripcion from fe_regimen_fiscal_sat fe where fe.codigo = grupos_ccont.regimen_fiscal) D_REGIMEN_FISCAL,(select nombre from tipos_grupos_Balance where empresa = grupos_ccont.empresa and codigo = grupos_ccont.tipo) D_TIPO,(SELECT lvtnif.descripcion FROM tipos_nif lvtnif WHERE lvtnif.tipo = GRUPOS_CCONT.TIPO_ENTIDAD AND lvtnif.estado = GRUPOS_CCONT.ESTADO) D_TIPO_ENTIDAD,(SELECT lvtia.descripcion FROM tipos_impuesto_alm lvtia WHERE lvtia.codigo = GRUPOS_CCONT.TIPO_IMPTO_ALM_EXENTO_OBRAS AND lvtia.empresa = GRUPOS_CCONT.EMPRESA) D_TIPO_IMPTO_ALM_EXENTO_OBRAS,(SELECT DESCRIPCION FROM TIPOS_IMPUESTO_GB WHERE CODIGO = GRUPOS_CCONT.TIPO_IMPUESTO_GB AND EMPRESA = GRUPOS_CCONT.EMPRESA) D_TIPO_IMPUESTO_GB,(SELECT A.NOMBRE FROM TIPOS_REPARTO A WHERE A.EMPRESA = GRUPOS_CCONT.EMPRESA AND A.TIPO_REPARTO = GRUPOS_CCONT.TIPO_REPARTO) D_TIPO_REPARTO 
FROM GRUPOS_CCONT) GRUPOS_CCONT 
WHERE EMPRESA = '004'                                                          